#!/bin/bash
# -- THE FILE IS AUTOGENERATED, DO NOT EDIT -- #
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=2
#SBATCH --partition=RT
#SBATCH --job-name=example
#SBATCH --comment="Run mpi from config"
#SBATCH --output=bin/out.txt
#SBATCH --error=bin/error.txt
mpiexec bin/MpiHomework 1000
